/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as EthicsRouteImport } from './routes/ethics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KaliIndexRouteImport } from './routes/kali.index'
import { Route as HackingIndexRouteImport } from './routes/hacking.index'
import { Route as KaliSlugRouteImport } from './routes/kali.$slug'
import { Route as HackingSlugRouteImport } from './routes/hacking.$slug'
import { Route as DistroSlugRouteImport } from './routes/distro.$slug'
import { Route as HackingSlugWalkthroughRouteImport } from './routes/hacking.$slug.walkthrough'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const EthicsRoute = EthicsRouteImport.update({
  id: '/ethics',
  path: '/ethics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KaliIndexRoute = KaliIndexRouteImport.update({
  id: '/kali/',
  path: '/kali/',
  getParentRoute: () => rootRouteImport,
} as any)
const HackingIndexRoute = HackingIndexRouteImport.update({
  id: '/hacking/',
  path: '/hacking/',
  getParentRoute: () => rootRouteImport,
} as any)
const KaliSlugRoute = KaliSlugRouteImport.update({
  id: '/kali/$slug',
  path: '/kali/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HackingSlugRoute = HackingSlugRouteImport.update({
  id: '/hacking/$slug',
  path: '/hacking/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DistroSlugRoute = DistroSlugRouteImport.update({
  id: '/distro/$slug',
  path: '/distro/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HackingSlugWalkthroughRoute = HackingSlugWalkthroughRouteImport.update({
  id: '/walkthrough',
  path: '/walkthrough',
  getParentRoute: () => HackingSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ethics': typeof EthicsRoute
  '/search': typeof SearchRoute
  '/distro/$slug': typeof DistroSlugRoute
  '/hacking/$slug': typeof HackingSlugRouteWithChildren
  '/kali/$slug': typeof KaliSlugRoute
  '/hacking/': typeof HackingIndexRoute
  '/kali/': typeof KaliIndexRoute
  '/hacking/$slug/walkthrough': typeof HackingSlugWalkthroughRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ethics': typeof EthicsRoute
  '/search': typeof SearchRoute
  '/distro/$slug': typeof DistroSlugRoute
  '/hacking/$slug': typeof HackingSlugRouteWithChildren
  '/kali/$slug': typeof KaliSlugRoute
  '/hacking': typeof HackingIndexRoute
  '/kali': typeof KaliIndexRoute
  '/hacking/$slug/walkthrough': typeof HackingSlugWalkthroughRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ethics': typeof EthicsRoute
  '/search': typeof SearchRoute
  '/distro/$slug': typeof DistroSlugRoute
  '/hacking/$slug': typeof HackingSlugRouteWithChildren
  '/kali/$slug': typeof KaliSlugRoute
  '/hacking/': typeof HackingIndexRoute
  '/kali/': typeof KaliIndexRoute
  '/hacking/$slug/walkthrough': typeof HackingSlugWalkthroughRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ethics'
    | '/search'
    | '/distro/$slug'
    | '/hacking/$slug'
    | '/kali/$slug'
    | '/hacking/'
    | '/kali/'
    | '/hacking/$slug/walkthrough'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ethics'
    | '/search'
    | '/distro/$slug'
    | '/hacking/$slug'
    | '/kali/$slug'
    | '/hacking'
    | '/kali'
    | '/hacking/$slug/walkthrough'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ethics'
    | '/search'
    | '/distro/$slug'
    | '/hacking/$slug'
    | '/kali/$slug'
    | '/hacking/'
    | '/kali/'
    | '/hacking/$slug/walkthrough'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EthicsRoute: typeof EthicsRoute
  SearchRoute: typeof SearchRoute
  DistroSlugRoute: typeof DistroSlugRoute
  HackingSlugRoute: typeof HackingSlugRouteWithChildren
  KaliSlugRoute: typeof KaliSlugRoute
  HackingIndexRoute: typeof HackingIndexRoute
  KaliIndexRoute: typeof KaliIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethics': {
      id: '/ethics'
      path: '/ethics'
      fullPath: '/ethics'
      preLoaderRoute: typeof EthicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kali/': {
      id: '/kali/'
      path: '/kali'
      fullPath: '/kali/'
      preLoaderRoute: typeof KaliIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hacking/': {
      id: '/hacking/'
      path: '/hacking'
      fullPath: '/hacking/'
      preLoaderRoute: typeof HackingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kali/$slug': {
      id: '/kali/$slug'
      path: '/kali/$slug'
      fullPath: '/kali/$slug'
      preLoaderRoute: typeof KaliSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hacking/$slug': {
      id: '/hacking/$slug'
      path: '/hacking/$slug'
      fullPath: '/hacking/$slug'
      preLoaderRoute: typeof HackingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distro/$slug': {
      id: '/distro/$slug'
      path: '/distro/$slug'
      fullPath: '/distro/$slug'
      preLoaderRoute: typeof DistroSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hacking/$slug/walkthrough': {
      id: '/hacking/$slug/walkthrough'
      path: '/walkthrough'
      fullPath: '/hacking/$slug/walkthrough'
      preLoaderRoute: typeof HackingSlugWalkthroughRouteImport
      parentRoute: typeof HackingSlugRoute
    }
  }
}

interface HackingSlugRouteChildren {
  HackingSlugWalkthroughRoute: typeof HackingSlugWalkthroughRoute
}

const HackingSlugRouteChildren: HackingSlugRouteChildren = {
  HackingSlugWalkthroughRoute: HackingSlugWalkthroughRoute,
}

const HackingSlugRouteWithChildren = HackingSlugRoute._addFileChildren(
  HackingSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EthicsRoute: EthicsRoute,
  SearchRoute: SearchRoute,
  DistroSlugRoute: DistroSlugRoute,
  HackingSlugRoute: HackingSlugRouteWithChildren,
  KaliSlugRoute: KaliSlugRoute,
  HackingIndexRoute: HackingIndexRoute,
  KaliIndexRoute: KaliIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
