/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KaliIndexRouteImport } from './routes/kali.index'
import { Route as KaliSlugRouteImport } from './routes/kali.$slug'
import { Route as DistroSlugRouteImport } from './routes/distro.$slug'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KaliIndexRoute = KaliIndexRouteImport.update({
  id: '/kali/',
  path: '/kali/',
  getParentRoute: () => rootRouteImport,
} as any)
const KaliSlugRoute = KaliSlugRouteImport.update({
  id: '/kali/$slug',
  path: '/kali/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DistroSlugRoute = DistroSlugRouteImport.update({
  id: '/distro/$slug',
  path: '/distro/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/distro/$slug': typeof DistroSlugRoute
  '/kali/$slug': typeof KaliSlugRoute
  '/kali/': typeof KaliIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/distro/$slug': typeof DistroSlugRoute
  '/kali/$slug': typeof KaliSlugRoute
  '/kali': typeof KaliIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/distro/$slug': typeof DistroSlugRoute
  '/kali/$slug': typeof KaliSlugRoute
  '/kali/': typeof KaliIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/search' | '/distro/$slug' | '/kali/$slug' | '/kali/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/search' | '/distro/$slug' | '/kali/$slug' | '/kali'
  id: '__root__' | '/' | '/search' | '/distro/$slug' | '/kali/$slug' | '/kali/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  DistroSlugRoute: typeof DistroSlugRoute
  KaliSlugRoute: typeof KaliSlugRoute
  KaliIndexRoute: typeof KaliIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kali/': {
      id: '/kali/'
      path: '/kali'
      fullPath: '/kali/'
      preLoaderRoute: typeof KaliIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kali/$slug': {
      id: '/kali/$slug'
      path: '/kali/$slug'
      fullPath: '/kali/$slug'
      preLoaderRoute: typeof KaliSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distro/$slug': {
      id: '/distro/$slug'
      path: '/distro/$slug'
      fullPath: '/distro/$slug'
      preLoaderRoute: typeof DistroSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  DistroSlugRoute: DistroSlugRoute,
  KaliSlugRoute: KaliSlugRoute,
  KaliIndexRoute: KaliIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
